a=int(input("Enter first number: "))
b=int(input("Enetr second number: "))
print("Addition ",a+b)
print("Subtraction ",a-b)
print("Multiplication ",a*b)
print("Division ",a/b)
print("Quotient",a//b)
print("square",a**b)
